// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "Rdtq_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// callViaXPtr
double callViaXPtr(const double x, SEXP xpsexp);
RcppExport SEXP Rdtq_callViaXPtr(SEXP xSEXP, SEXP xpsexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xpsexp(xpsexpSEXP);
    rcpp_result_gen = Rcpp::wrap(callViaXPtr(x, xpsexp));
    return rcpp_result_gen;
END_RCPP
}
// rdtq
NumericVector rdtq(double h, double k, int bigm, double init, double T, SEXP driftsexp, SEXP diffsexp);
RcppExport SEXP Rdtq_rdtq(SEXP hSEXP, SEXP kSEXP, SEXP bigmSEXP, SEXP initSEXP, SEXP TSEXP, SEXP driftsexpSEXP, SEXP diffsexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type bigm(bigmSEXP);
    Rcpp::traits::input_parameter< double >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< SEXP >::type driftsexp(driftsexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type diffsexp(diffsexpSEXP);
    rcpp_result_gen = Rcpp::wrap(rdtq(h, k, bigm, init, T, driftsexp, diffsexp));
    return rcpp_result_gen;
END_RCPP
}
