// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "Rdtq_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// putFunPtrInXPtr
XPtr<funcPtr> putFunPtrInXPtr(std::string fstr);
RcppExport SEXP Rdtq_putFunPtrInXPtr(SEXP fstrSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fstr(fstrSEXP);
    __result = Rcpp::wrap(putFunPtrInXPtr(fstr));
    return __result;
END_RCPP
}
// callViaString
arma::vec callViaString(const arma::vec x, std::string funname);
RcppExport SEXP Rdtq_callViaString(SEXP xSEXP, SEXP funnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type funname(funnameSEXP);
    __result = Rcpp::wrap(callViaString(x, funname));
    return __result;
END_RCPP
}
